/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.ducvuongcity.contact.xml -p ContactInterface
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CONTACTINTERFACE_H_1500437066
#define CONTACTINTERFACE_H_1500437066

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.ducvuongcity.contact
 */
class ComDucvuongcityContactInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.ducvuongcity.contact"; }

public:
    ComDucvuongcityContactInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComDucvuongcityContactInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void sgn_sendContact(const QString &name, const QString &number);
    void sgn_sendReply(const QString &msg);
};

namespace com {
  namespace ducvuongcity {
    typedef ::ComDucvuongcityContactInterface contact;
  }
}
#endif
