/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.ducvuongcity.contact.xml -a ContactAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONTACTADAPTOR_H_1500437113
#define CONTACTADAPTOR_H_1500437113

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.ducvuongcity.contact
 */
class ContactAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.ducvuongcity.contact")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.ducvuongcity.contact\">\n"
"    <signal name=\"sgn_sendContact\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"number\"/>\n"
"    </signal>\n"
"    <signal name=\"sgn_sendReply\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msg\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ContactAdaptor(QObject *parent);
    virtual ~ContactAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void sgn_sendContact(const QString &name, const QString &number);
    void sgn_sendReply(const QString &msg);
};

#endif
